services:
  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=cercli

  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - "8888:8080"
