specs:
  currency:
    supported-currencies:
      - USD
  employee:
    max-full-name-length: 200
  leave-request:
    supported-types:
      - "SICK_LEAVE"
      - "ANNUAL_LEAVE"
      - "WORK_REMOTELY"
    overlapping-types:
      "WORK_REMOTELY":
        - "ANNUAL_LEAVE"
